version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server

    hostname: rabbitmq

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - traefik_public
    #ports:
    #  - 5672:5672
    #  - 15672:15672

    environment:
      ## Dados de acesso
      RABBITMQ_DEFAULT_USER: @450Ab6606289828rabbitmq
      RABBITMQ_DEFAULT_PASS: 25eb2facbc2e525b034339927779349c
      RABBITMQ_ERLANG_COOKIE: e195510b1e1a5984be7542d0b569a9a1
      RABBITMQ_DEFAULT_VHOST: "/"

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.b7g.app`)
        - traefik.http.routers.rabbitmq.entrypoints=websecure
        - traefik.http.routers.rabbitmq.tls.certresolver=letsencryptresolver
        - traefik.http.routers.rabbitmq.service=rabbitmq
        - traefik.http.services.rabbitmq.loadbalancer.server.port=15672

## --------------------------- ORION --------------------------- ##

volumes:
  rabbitmq_data:
    external: true

networks:
  traefik_public:
    external: true
