version: "3.8"

services:
  n8n_mcp_api:
    image: n8nio/n8n:1.101.1
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    command: start
    user: "1000:1000"
    
    networks:
      - app_network     # Conecta com PostgreSQL/Redis
      - traefik_public      # Exposição via Traefik
    
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_files:/files
    
    environment:
      
      # Configurações Gerais do N8N
      
      # ALTERE: Gere uma nova chave forte
      - N8N_ENCRYPTION_KEY=KRpMlPWMnUPpJ4Ehy6sHuYYweuLes4RT
      - NODE_ENV=production
      - N8N_METRICS=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PAYLOAD_SIZE_MAX=16
      - N8N_LOG_LEVEL=info
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      
      # Task Runners (habilitados para performance)
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      
      
      # Configuração do Banco de Dados - CORRIGIDO
      
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_database              
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=app_user                      
      - DB_POSTGRESDB_PASSWORD=4hwM-An0+14dC=z 
      
      
      # Configuração do Endereço do N8N - ALTERE DOMÍNIOS
      
      - N8N_PORT=5678
      - N8N_HOST=editor.seudominio.com
      - N8N_EDITOR_BASE_URL=https://editor.seudominio.com/
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://workflow.seudominio.com/
      - N8N_ENDPOINT_WEBHOOK=webhook
      
      
      # Configuração da Fila (Redis) - AJUSTE SENHA
      
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - QUEUE_BULL_REDIS_PASSWORD=1H9PvFRv1BAc  # MESMA SENHA DO REDIS
      - EXECUTIONS_TIMEOUT=3600      # 1 hora
      - EXECUTIONS_TIMEOUT_MAX=7200  # 2 horas
      
      
      # Interface do N8N
      
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_WORKFLOW_TAGS_DISABLED=false
      - N8N_HIDE_USAGE_PAGE=false
      
      
      # Limpeza e Manutenção
      
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336           # 2 semanas
      - EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL=15
      - EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL=60
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=false
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      
      
      # Bibliotecas e Packages
      
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=lodash,moment,axios
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      
      
      # IA (opcional)
      
      - N8N_AI_ENABLED=false
      # - N8N_AI_PROVIDER=openai
      # - N8N_AI_OPENAI_API_KEY=sua_chave_openai
      
      
      # E-mail (Multi-user) - CONFIGURE SMTP
      
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=seuemail@gmail.com
      - N8N_SMTP_PASS=suasenha
      - N8N_SMTP_SENDER=seuemail@gmail.com
      - N8N_SMTP_SSL=false
      - N8N_SMTP_SECURE=false
      - N8N_SMTP_TLS=true
    
    deploy:
      mode: replicated
      replicas: 1
      
      placement:
        constraints:
          - node.role == manager
      
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.5"
          memory: 1024M
      
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik_public
        
        # Middleware para remover gzip
        - traefik.http.middlewares.nogzip.headers.customResponseHeaders.Content-Encoding=""
        
        # Router para MCP API
        - traefik.http.routers.n8n_mcp_api.rule=Host(`workflow.seudominio.com`) && PathPrefix(`/mcp`)
        - traefik.http.routers.n8n_mcp_api.entrypoints=websecure
        - traefik.http.routers.n8n_mcp_api.tls.certresolver=letsencrypt
        - traefik.http.routers.n8n_mcp_api.service=n8n_mcp_api
        - traefik.http.routers.n8n_mcp_api.middlewares=nogzip
        - traefik.http.services.n8n_mcp_api.loadbalancer.server.port=5678
        - traefik.http.services.n8n_mcp_api.loadbalancer.passHostHeader=true
      
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback
        monitor: 60s
      
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    
    # Healthcheck para webhook service
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s

networks:
  app_network:
    external: true
  traefik_public:
    external: true

volumes:
  n8n_data:
    driver: local
  n8n_files: 
    driver: local
