version: "3.8"

services:
  supabase_migrate:
    image: postgres:16-alpine
    networks:
      - app_network
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=chatwoot_database
      - PGPASSWORD=Ma1x1x0x!!Ma1x1x0x!!
      - PGDATABASE=postgres
    entrypoint: ["sh", "-c"]
    command: >
      echo 'Waiting for PostgreSQL...' &&
      until pg_isready -h postgres -p 5432 -U chatwoot_database; do sleep 2; done &&
      echo 'PostgreSQL ready! Creating database...' &&
      psql -h postgres -U chatwoot_database -d postgres -lqt | cut -d '|' -f 1 | grep -qw supabase_db || psql -h postgres -U chatwoot_database -d postgres -c 'CREATE DATABASE supabase_db;' &&
      echo 'Creating extensions...' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE EXTENSION IF NOT EXISTS vector;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE EXTENSION IF NOT EXISTS pg_stat_statements;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE EXTENSION IF NOT EXISTS pgcrypto;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE EXTENSION IF NOT EXISTS pgjwt;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE EXTENSION IF NOT EXISTS uuid-ossp;' &&
      echo 'Creating schemas...' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE SCHEMA IF NOT EXISTS auth;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE SCHEMA IF NOT EXISTS storage;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE SCHEMA IF NOT EXISTS realtime;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE SCHEMA IF NOT EXISTS graphql_public;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE SCHEMA IF NOT EXISTS extensions;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE SCHEMA IF NOT EXISTS pgsodium;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE SCHEMA IF NOT EXISTS pgsodium_masks;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE SCHEMA IF NOT EXISTS vault;' &&
      echo 'Creating roles...' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE ROLE anon NOLOGIN;' || true &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE ROLE authenticated NOLOGIN;' || true &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE ROLE service_role NOLOGIN SUPERUSER;' || true &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE ROLE supabase_admin LOGIN SUPERUSER PASSWORD '\''Ma1x1x0x!!Ma1x1x0x!!'\'';' || true &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'CREATE ROLE authenticator LOGIN PASSWORD '\''Ma1x1x0x!!Ma1x1x0x!!'\'' NOINHERIT;' || true &&
      echo 'Granting permissions...' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'GRANT anon TO authenticator;' || true &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'GRANT authenticated TO authenticator;' || true &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'GRANT service_role TO authenticator;' || true &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'ALTER SCHEMA auth OWNER TO supabase_admin;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'ALTER SCHEMA storage OWNER TO supabase_admin;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'ALTER SCHEMA realtime OWNER TO supabase_admin;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'ALTER SCHEMA graphql_public OWNER TO supabase_admin;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'GRANT ALL ON SCHEMA auth TO supabase_admin;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'GRANT ALL ON SCHEMA storage TO supabase_admin;' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'GRANT ALL ON SCHEMA realtime TO supabase_admin;' &&
      echo 'Setting RLS...' &&
      psql -h postgres -U chatwoot_database -d supabase_db -c 'ALTER DATABASE supabase_db SET row_security = on;' &&
      echo 'Supabase setup completed successfully!'
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  app_network:
    external: true


    