version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  calcom:
    image: calcom/cal.com:v4.7.8

    networks:
      - traefik_public

    #depends_on:
    #  - postgres

    environment:
    ## Licenças
      - NEXT_PUBLIC_LICENSE_CONSENT=agree
      - LICENSE=agree
      #- CALCOM_LICENSE_KEY= ## Descomente este campo caso tenha licença do mesmo

    ## URLs
      - NEXT_PUBLIC_WEBAPP_URL=https://cal.senaia.in
      - BASE_URL=https://cal.senaia.in
      - NEXTAUTH_URL=https://cal.senaia.in
      - NEXT_PUBLIC_CONSOLE_URL=https://cal.senaia.in
      - NEXT_PUBLIC_APP_URL=https://cal.senaia.in
      - NEXT_PUBLIC_WEBSITE_URL=https://cal.senaia.in
      - WEB_APP=https://cal.senaia.in

    ## Encrypition
      - NEXTAUTH_SECRET=0fc7aa49b39cb7d0f598e13121e2695c 
      - CALENDSO_ENCRYPTION_KEY=0fc7aa49b39cb7d0f598e13121e2695c

    ## Dados Postgress
      - DATABASE_URL=postgresql://postgres:6751e826ba4f6b8f4e8640001316d85f@postgres:5432/calcom
      - DATABASE_DIRECT_URL=postgresql://postgres:6751e826ba4f6b8f4e8640001316d85f@postgres:5432/calcom

    ## Configurações de Email e SMTP
      - EMAIL_FROM=marcelu.phd@gmail.com
      - EMAIL_SERVER_HOST=smtp.gmail.com
      - EMAIL_SERVER_PORT=587
      - EMAIL_SERVER_USER=marcelu.phd@gmail.com
      - EMAIL_SERVER_PASSWORD=dmaatsjzgzxqxmil

    ## Nodes
      - NODE_ENV=production
      - PORT=3001  # Use port 3001 instead of 3000 to avoid conflict
      - NEXT_PUBLIC_WEBAPP_PORT=3001  # Inform Next.js about the new port
      - HOST=0.0.0.0  # Bind to all interfaces
      - NEXT_PUBLIC_VERCEL_URL=https://cal.senaia.in
      #- NODE_TLS_REJECT_UNAUTHORIZED=0

    ## Brand
      #- NEXT_PUBLIC_APP_NAME="Cal.com"
      #- NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS="help@cal.com"
      #- NEXT_PUBLIC_COMPANY_NAME="Cal.com, Inc."
      #- NEXT_PUBLIC_DISABLE_SIGNUP=false ## false = novas inscrições permitidas | true = novas incrições fechadas

    ## Integração com Google (Calendario & Meet)
      #-GOOGLE_LOGIN_ENABLED=false
      #-GOOGLE_API_CREDENTIALS=

    ## Integração com Microsoft 365
      #- MS_GRAPH_CLIENT_ID=
      #- MS_GRAPH_CLIENT_SECRET=

    ## Integração com Zoom
      #- ZOOM_CLIENT_ID=
      #- ZOOM_CLIENT_SECRET=

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.calcom_app.rule=Host(`cal.senaia.in`)
        - traefik.http.routers.calcom_app.entrypoints=websecure
        - traefik.http.routers.calcom_app.priority=1
        - traefik.http.routers.calcom_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.calcom_app.service=calcom_app
        - traefik.http.services.calcom_app.loadbalancer.server.port=3001
        - traefik.http.services.calcom_app.loadbalancer.passHostHeader=1

## --------------------------- ORION --------------------------- ##

networks:
  traefik_public:
    name: traefik_public
    external: true
