version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  chatwoot_app:
    image: chatwoot/chatwoot:v4.1.0 ## Versão do Chatwoot
    command: >
      sh -c "echo 'Rails.application.config.active_storage.variant_processor = :mini_magick' > /app/config/initializers/active_storage.rb && bundle exec rails s -p 3002 -b 0.0.0.0 -e production"
    entrypoint: docker/entrypoints/rails.sh

    volumes:
      - chatwoot_storage:/app/storage ## Arquivos de conversa
      - chatwoot_public:/app/public ## Arquivos de logos
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails

    networks:
      - traefik_public ## Nome da rede interna

    environment:
    ## 🌐 Qualquer Url com # no final
      #- CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#

    ## 🏢 Nome da Empresa
      - INSTALLATION_NAME=paraguays

    ## 🔐 Secret key
      - SECRET_KEY_BASE=f3ecd41116c93fe47bb233ed4a3f83e1

    ## 💬 Url Chatwoot
      - FRONTEND_URL=https://chat.senaia.in
      - FORCE_SSL=true
      - PORT=3002  # Explicitly set port for Chatwoot

    ## 🌍 Idioma/Localização padrão
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo

    ## ☁️ Google Cloud - Modifique de acordo com os seus dados
      #- GOOGLE_OAUTH_CLIENT_ID=369777777777-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      #- GOOGLE_OAUTH_CLIENT_SECRET=ABCDEF-GHijklmnoPqrstuvwX-yz1234567
      #- GOOGLE_OAUTH_CALLBACK_URL=https://<your-server-domain>/omniauth/google_oauth2/callback

    ## 🔐 Facebook e Instagram
      #- IG_VERIFY_TOKEN=
      #- FB_VERIFY_TOKEN=
      #- FB_APP_SECRET=
      #- FB_APP_ID=

    ## 🧑‍💻 Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6381

    ## 🗄️ Dados do Postgres
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=5531fb71736bebeddca5abc3b385c812 ## Senha do postgres
      - POSTGRES_DATABASE=chatwoot

    ## 🏠 Armazenamento
      - ACTIVE_STORAGE_SERVICE=local ## use s3_compatible para MinIO
      #- STORAGE_BUCKET_NAME=chatwoot
      #- STORAGE_ACCESS_KEY_ID=ACCESS_KEY_MINIO
      #- STORAGE_SECRET_ACCESS_KEY=SECRET_KEY_MINIO
      #- STORAGE_REGION=eu-south
      #- STORAGE_ENDPOINT=https://s3.DOMINIO.COM
      #- STORAGE_FORCE_PATH_STYLE=true

    ## 📧 Dados do SMTP
      - MAILER_SENDER_EMAIL=marcelu.phd@gmail.com <marcelu.phd@gmail.com> ## Email SMTP
      - SMTP_DOMAIN=gmail.com ## Dominio do email
      - SMTP_ADDRESS=smtp.gmail.com ## Host SMTP
      - SMTP_PORT=587 ## Porta SMTP
      - SMTP_SSL=false ## Se a porta for 465 = true | Se a porta for 587 = false
      - SMTP_USERNAME=marcelu.phd@gmail.com ## Usuario SMTP
      - SMTP_PASSWORD=dmaatsjzgzxqxmil ## Senha do SMTP
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=marcelu.phd@gmail.com ## Email SMTP

    ## ⚙️ Melhorias
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false

    ## ⚡ Outras configurações
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_app.rule=Host(`chat.senaia.in`)
        - traefik.http.routers.chatwoot_app.entrypoints=websecure
        - traefik.http.routers.chatwoot_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot_app.priority=1
        - traefik.http.routers.chatwoot_app.service=chatwoot_app
        - traefik.http.services.chatwoot_app.loadbalancer.server.port=3002
        - traefik.http.services.chatwoot_app.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=sslheader

## --------------------------- ORION --------------------------- ##

  chatwoot_sidekiq:
    image: chatwoot/chatwoot:v4.1.0 ## Versão do Chatwoot
    command: bundle exec sidekiq -C config/sidekiq.yml

    volumes:
      - chatwoot_storage:/app/storage ## Arquivos de conversa
      - chatwoot_public:/app/public ## Arquivos de logos
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails

    networks:
      - traefik_public ## Nome da rede interna

    environment:
    ## 🌐 Qualquer Url com # no final
      #- CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#

    ## 🏢 Nome da Empresa
      - INSTALLATION_NAME=paraguays

    ## 🔐 Secret key
      - SECRET_KEY_BASE=f3ecd41116c93fe47bb233ed4a3f83e1

    ## 💬 Url Chatwoot
      - FRONTEND_URL=https://chat.senaia.in
      - FORCE_SSL=true

    ## 🌍 Idioma/Localização padrão
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo

    ## ☁️ Google Cloud - Modifique de acordo com os seus dados
      #- GOOGLE_OAUTH_CLIENT_ID=369777777777-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      #- GOOGLE_OAUTH_CLIENT_SECRET=ABCDEF-GHijklmnoPqrstuvwX-yz1234567
      #- GOOGLE_OAUTH_CALLBACK_URL=https://<your-server-domain>/omniauth/google_oauth2/callback

    ## 🔐 Facebook e Instagram
      #- IG_VERIFY_TOKEN=
      #- FB_VERIFY_TOKEN=
      #- FB_APP_SECRET=
      #- FB_APP_ID=

    ## 🧑‍💻 Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6381

    ## 🗄️ Dados do Postgres
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=5531fb71736bebeddca5abc3b385c812 ## Senha do postgres
      - POSTGRES_DATABASE=chatwoot

    ## 🏠 Armazenamento
      - ACTIVE_STORAGE_SERVICE=local ## use s3_compatible para MinIO
      #- STORAGE_BUCKET_NAME=chatwoot
      #- STORAGE_ACCESS_KEY_ID=ACCESS_KEY_MINIO
      #- STORAGE_SECRET_ACCESS_KEY=SECRET_KEY_MINIO
      #- STORAGE_REGION=eu-south
      #- STORAGE_ENDPOINT=https://s3.DOMINIO.COM
      #- STORAGE_FORCE_PATH_STYLE=true

    ## 📧 Dados do SMTP
      - MAILER_SENDER_EMAIL=marcelu.phd@gmail.com <marcelu.phd@gmail.com> ## Email SMTP
      - SMTP_DOMAIN=gmail.com ## Dominio do email
      - SMTP_ADDRESS=smtp.gmail.com ## Host SMTP
      - SMTP_PORT=587 ## Porta SMTP
      - SMTP_SSL=false ## Se a porta for 465 = true | Se a porta for 587 = false
      - SMTP_USERNAME=marcelu.phd@gmail.com ## Usuario SMTP
      - SMTP_PASSWORD=dmaatsjzgzxqxmil ## Senha do SMTP
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=marcelu.phd@gmail.com ## Email SMTP

    ## ⚙️ Melhorias
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false

    ## ⚡ Outras configurações
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- ORION --------------------------- ##

  chatwoot_redis:
    image: redis:latest  ## Versão do Redis
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6381"
      ]

    volumes:
      - chatwoot_redis:/data

    networks:
      - traefik_public ## Nome da rede interna

    ## Descomente as linhas abaixo para uso externo
    #ports:
    #  - 6381:6381

    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- ORION --------------------------- ##

volumes:
  chatwoot_storage:
    external: true
    name: chatwoot_storage
  chatwoot_public:
    external: true
    name: chatwoot_public
  chatwoot_mailer:
    external: true
    name: chatwoot_mailer
  chatwoot_mailers:
    external: true
    name: chatwoot_mailers
  chatwoot_redis:
    external: true
    name: chatwoot_redis

networks:
  traefik_public: ## Nome da rede interna
    external: true
    name: traefik_public ## Nome da rede interna
