version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  pgvector:
    image: pgvector/pgvector:pg16 ## Versão do PgVector
    command: >
      postgres
      -c max_connections=500
      -c shared_buffers=512MB
      -c timezone=America/Sao_Paulo

    volumes:
      - pgvector:/var/lib/postgresql/data

    networks:
      - traefik_public ## Nome da rede interna

    ## External port access to avoid conflict with main postgres
    ports:
      - 5433:5432

    environment:
      ## 🔑 Senha do Postgres 
      - POSTGRES_PASSWORD=5531fb71736bebeddca5abc3b385c812

      ## 🌎 Timezone
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- ORION --------------------------- ##

volumes:
  pgvector:
    external: true
    name: pgvector

networks:
  traefik_public: ## Nome da rede interna
    external: true
    name: traefik_public ## Nome da rede interna
