version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server

    hostname: rabbitmq

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - traefik_public
    #ports:
    #  - 5672:5672
    #  - 15672:15672

    environment:
      ## Dados de acesso
      RABBITMQ_DEFAULT_USER: marcelu.phd@gmail.com
      RABBITMQ_DEFAULT_PASS: 20ebc5a06b668f0f430dc3c046a9b797
      RABBITMQ_ERLANG_COOKIE: d38cba8dec3e9ced1734916d0e7f2a46
      RABBITMQ_DEFAULT_VHOST: "/"

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.senaia.in`)
        - traefik.http.routers.rabbitmq.entrypoints=websecure
        - traefik.http.routers.rabbitmq.tls.certresolver=letsencryptresolver
        - traefik.http.routers.rabbitmq.service=rabbitmq
        - traefik.http.services.rabbitmq.loadbalancer.server.port=15672

## --------------------------- ORION --------------------------- ##

volumes:
  rabbitmq_data:
    external: true

networks:
  traefik_public:
    external: true
