version: "3.8"

services:
  calcom:
    image: calcom/cal.com:v3.7.11
    ports:
      - 6000:3000
    networks:
      - network_public

    environment:
    ## Licenças
      - NEXT_PUBLIC_LICENSE_CONSENT=agree
      - LICENSE=agree
      #- CALCOM_LICENSE_KEY= ## Descomente este campo caso tenha licença

    ## URLs
      - NEXT_PUBLIC_WEBAPP_URL=https://agenda.senaia-bank.in
      - BASE_URL=https://agenda.senaia-bank.in
      - NEXTAUTH_URL=https://agenda.senaia-bank.in
      - NEXT_PUBLIC_CONSOLE_URL=https://agenda.senaia-bank.in
      - NEXT_PUBLIC_APP_URL=https://agenda.senaia-bank.in
      - NEXT_PUBLIC_WEBSITE_URL=https://agenda.senaia-bank.in
      - WEB_APP=https://agenda.senaia-bank.in

    ## Encrypition
      - NEXTAUTH_SECRET=rodc24e7b3a5a048b3caa760f2ac724f 
      - CALENDSO_ENCRYPTION_KEY=rodc24e7b3a5a048b3caa760f2ac724f

    ## Dados Postgress
      - DATABASE_URL=postgresql://postgres:Ma1x1x0x!!Ma1x1x0x!!@postgres:5432/calcom

    ## Configurações de Email e SMTP
      - EMAIL_FROM=projetoslinux@gmail.com
      - EMAIL_SERVER_HOST=smtp.gmail.com
      - EMAIL_SERVER_PORT=587
      - EMAIL_SERVER_USER=projetoslinux@gmail.com
      - EMAIL_SERVER_PASSWORD=ycprykpgjfzmblou

    ## Nodes
      - NODE_ENV=production
      #- NODE_TLS_REJECT_UNAUTHORIZED=0

    ## Brand
      #- NEXT_PUBLIC_APP_NAME="Cal.com"
      #- NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS="help@cal.com"
      #- NEXT_PUBLIC_COMPANY_NAME="Cal.com, Inc."
      - NEXT_PUBLIC_DISABLE_SIGNUP=true ## false = novas inscrições permitidas | true = novas incrições fechadas

    ## Integração com Microsoft 365
      #- MS_GRAPH_CLIENT_ID=
      #- MS_GRAPH_CLIENT_SECRET=

    ## Integração com Zoom
      #- ZOOM_CLIENT_ID=
      #- ZOOM_CLIENT_SECRET=

    ## Integração Google
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=true
      - traefik.http.routers.calcom.rule=Host(`agenda.senaia-bank.in`)
      - traefik.http.routers.calcom.entrypoints=websecure
      - traefik.http.routers.calcom.priority=1
      - traefik.http.routers.calcom.tls.certresolver=letsencryptresolver
      - traefik.http.routers.calcom.service=calcom
      - traefik.http.services.calcom.loadbalancer.server.port=3000
      - traefik.http.services.calcom.loadbalancer.passHostHeader=1

networks:
  network_public:
    name: network_public
    external: true


# access container postgres in terminal     
# psql -U postgres 
# create database calcom;
# enter google developer console and create a new project
# create a new client id and client secret
# enter the client id and client secret in the .env file
# restart the container
# access the container in terminal and run the following command
# place url to callback    https://agenda.senaia-bank.in/api/integrations/googlecalendar/callback
# manager google account -- enable 2. etapa verifyin your google account searche senha app -- create agenda and place smtp password

# [REMOVED FOR SECURITY]
# go to settings security and 2 factor authentication and enable it and create with google auth
# select app with https://agenda.senaia-bank.in/api/integrations/googlecalendar/callback
# [GOOGLE_CLIENT_ID]
# [GOOGLE_CLIENT_SECRET]