version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  chatwoot_app:
    image: ghcr.io/fazer-ai/chatwoot:latest ## Versão do Chatwoot
    command: >
       sh -c "bundle exec rails db:chatwoot_prepare && bundle exec rails branding:update && if [ -n "$${BRAND_ASSETS_URL}" ]; then deployment/extract_brand_assets.sh "$${BRAND_ASSETS_URL}"; fi && bundle exec rails s -p 3040 -b 0.0.0.0"t: docker/entrypoints/rails.sh
      #sh -c "echo 'Rails.application.config.active_storage.variant_processor = :mini_magick' > /app/config/initializers/active_storage.rb && bundle exec rails s -p 3000 -b 0.0.0.0"
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - chatwoot_storage:/app/storage ## Arquivos de conversa
      - chatwoot_public:/app/public ## Arquivos de logos
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails

    networks:
      - traefik_public ## Nome da rede interna
    
    environment:
    ## 🌐 Qualquer Url com # no final
      #- CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#

    ## 🏢 Nome da Empresa
      - INSTALLATION_NAME=paraguays

    ## 🔐 Secret key
      - SECRET_KEY_BASE=9d4b5b5b59686016c5b2556318a571bd

    ## 💬 Url Chatwoot
      - FRONTEND_URL=https://chat.b7g.app
      - FORCE_SSL=true

    ## 🌍 Idioma/Localização padrão
      - DEFAULT_LOCALE=es_PY
      - TZ=America/Asuncion

    ## ☁️ Google Cloud - Modifique de acordo com os seus dados
      #- GOOGLE_OAUTH_CLIENT_ID=369777777777-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      #- GOOGLE_OAUTH_CLIENT_SECRET=ABCDEF-GHijklmnoPqrstuvwX-yz1234567
      #- GOOGLE_OAUTH_CALLBACK_URL=https://<your-server-domain>/omniauth/google_oauth2/callback

    ## 🔐 Facebook e Instagram
      #- IG_VERIFY_TOKEN=
      #- FB_VERIFY_TOKEN=
      #- FB_APP_SECRET=
      #- FB_APP_ID=

    ## 🧑‍💻 Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6379

    ## 🗄️ Dados do Postgres
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=3e6a2e1d5861027de8327f2145bab206 ## Senha do postgres
      - POSTGRES_DATABASE=chatwoot

    ## 🏠 Armazenamento
      - ACTIVE_STORAGE_SERVICE=local ## use s3_compatible para MinIO
      #- STORAGE_BUCKET_NAME=chatwoot
      #- STORAGE_ACCESS_KEY_ID=ACCESS_KEY_MINIO
      #- STORAGE_SECRET_ACCESS_KEY=SECRET_KEY_MINIO
      #- STORAGE_REGION=eu-south
      #- STORAGE_ENDPOINT=https://s3.DOMINIO.COM
      #- STORAGE_FORCE_PATH_STYLE=true

    ## 📧 Dados do SMTP
      - MAILER_SENDER_EMAIL=marcelu.phd@gmail.com <marcelu.phd@gmail.com> ## Email SMTP
      - SMTP_DOMAIN=gmail.com ## Dominio do email
      - SMTP_ADDRESS=smtp.gmail.com ## Host SMTP
      - SMTP_PORT=587 ## Porta SMTP
      - SMTP_SSL=false ## Se a porta for 465 = true | Se a porta for 587 = false
      - SMTP_USERNAME=marcelu.phd@gmail.com ## Usuario SMTP
      - SMTP_PASSWORD=LcXEtOWi3xX0HNFY4EbMT9sPWcMbT1nu194F83A5E420E2898283782FE1E64C2E7C07B5C3F7409BA90138E2D1E658BD77 ## Senha do SMTP
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=marcelu.phd@gmail.com ## Email SMTP

    ## ⚙️ Melhorias
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false

    ## ⚡ Outras configurações
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false

      # Baileys Provider Configuration
      - BAILEYS_PROVIDER_DEFAULT_CLIENT_NAME=chatwoot_app
      - BAILEYS_PROVIDER_DEFAULT_URL=http://baileys_app:3025
      - BAILEYS_PROVIDER_DEFAULT_API_KEY=194F83A5E420E2898283782FE1E64C2E7C07B5C3F7409BA90138E2D1E658BD77
      - BAILEYS_PROVIDER_USE_INTERNAL_HOST_URL=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_app.rule=Host(`chat.b7g.app`)
        - traefik.http.routers.chatwoot_app.entrypoints=websecure
        - traefik.http.routers.chatwoot_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot_app.priority=1
        - traefik.http.routers.chatwoot_app.service=chatwoot_app
        - traefik.http.services.chatwoot_app.loadbalancer.server.port=3000
        - traefik.http.services.chatwoot_app.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=sslheader

## --------------------------- ORION --------------------------- ##

  chatwoot_sidekiq:
    image: ghcr.io/fazer-ai/chatwoot:latest ## Versão do Chatwoot
    command: bundle exec sidekiq -C config/sidekiq.yml

    volumes:
      - chatwoot_storage:/app/storage ## Arquivos de conversa
      - chatwoot_public:/app/public ## Arquivos de logos
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails

    networks:
      - traefik_public ## Nome da rede interna

    environment:
    ## 🌐 Qualquer Url com # no final
      #- CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#

    ## 🏢 Nome da Empresa
      - INSTALLATION_NAME=paraguays

    ## 🔐 Secret key
      - SECRET_KEY_BASE=9d4b5b5b59686016c5b2556318a571bd

    ## 💬 Url Chatwoot
      - FRONTEND_URL=https://chat.b7g.app
      - FORCE_SSL=true

    ## 🌍 Idioma/Localização padrão
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo

    ## ☁️ Google Cloud - Modifique de acordo com os seus dados
      #- GOOGLE_OAUTH_CLIENT_ID=369777777777-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      #- GOOGLE_OAUTH_CLIENT_SECRET=ABCDEF-GHijklmnoPqrstuvwX-yz1234567
      #- GOOGLE_OAUTH_CALLBACK_URL=https://<your-server-domain>/omniauth/google_oauth2/callback

    ## 🔐 Facebook e Instagram
      #- IG_VERIFY_TOKEN=
      #- FB_VERIFY_TOKEN=
      #- FB_APP_SECRET=
      #- FB_APP_ID=

    ## 🧑‍💻 Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6379

    ## 🗄️ Dados do Postgres
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=3e6a2e1d5861027de8327f2145bab206 ## Senha do postgres
      - POSTGRES_DATABASE=chatwoot

    ## 🏠 Armazenamento
      - ACTIVE_STORAGE_SERVICE=local ## use s3_compatible para MinIO
      #- STORAGE_BUCKET_NAME=chatwoot
      #- STORAGE_ACCESS_KEY_ID=ACCESS_KEY_MINIO
      #- STORAGE_SECRET_ACCESS_KEY=SECRET_KEY_MINIO
      #- STORAGE_REGION=eu-south
      #- STORAGE_ENDPOINT=https://s3.DOMINIO.COM
      #- STORAGE_FORCE_PATH_STYLE=true

    ## 📧 Dados do SMTP
      - MAILER_SENDER_EMAIL=marcelu.phd@gmail.com <marcelu.phd@gmail.com> ## Email SMTP
      - SMTP_DOMAIN=gmail.com ## Dominio do email
      - SMTP_ADDRESS=smtp.gmail.com ## Host SMTP
      - SMTP_PORT=587 ## Porta SMTP
      - SMTP_SSL=false ## Se a porta for 465 = true | Se a porta for 587 = false
      - SMTP_USERNAME=marcelu.phd@gmail.com ## Usuario SMTP
      - SMTP_PASSWORD=edmoauhradsarvmw ## Senha do SMTP
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=marcelu.phd@gmail.com ## Email SMTP

    ## ⚙️ Melhorias
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false

    ## ⚡ Outras configurações
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false

      # Features
      - ENABLE_PUSH_RELAY_SERVER=true
      - IOS_APP_ID=L7YLMN4634.com.chatwoot.app
      - ANDROID_BUNDLE_ID=com.chatwoot.app
      - ANDROID_SHA256_CERT_FINGERPRINT=AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8

      # Baileys Provider Configuration
      - BAILEYS_PROVIDER_DEFAULT_CLIENT_NAME=chatwoot_app
      - BAILEYS_PROVIDER_DEFAULT_URL=http://baileys_app:3025
      - BAILEYS_PROVIDER_DEFAULT_API_KEY=194F83A5E420E2898283782FE1E64C2E7C07B5C3F7409BA90138E2D1E658BD77
      - BAILEYS_PROVIDER_USE_INTERNAL_HOST_URL=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- ORION --------------------------- ##

  chatwoot_redis:
    image: redis:latest  ## Versão do Redis
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]

    volumes:
      - chatwoot_redis:/data

    networks:
      - traefik_public ## Nome da rede interna

    ## Descomente as linhas abaixo para uso externo
    #ports:
    #  - 6379:6379

    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- ORION --------------------------- ##

  # Baileys API Service
  baileys_app:
    image: "ghcr.io/fazer-ai/baileys-api:latest"
    command: >
      sh -c "bun manage-api-keys create user 194F83A5E420E2898283782FE1E64C2E7C07B5C3F7409BA90138E2D1E658BD77 && bun start"

    networks:
      - traefik_public

    volumes:
      - chatwoot_baileys:/app/storage

    environment:
    
    ## 🧑‍💻 Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6379

      # Logging configuration
      - LOG_LEVEL=info
      - BAILEYS_LOG_LEVEL=error

      # API Key configuration
      - BAILEYS_PROVIDER_DEFAULT_API_KEY=194F83A5E420E2898283782FE1E64C2E7C07B5C3F7409BA90138E2D1E658BD77

      # CORS and Webhook configuration
      - CORS_ORIGIN=*
      - WEBHOOK_URL=https://baileys.b7g.app/webhooks/whatsapp
      - WEBHOOK_ENABLED=true

    deploy:
      mode: replicated
      replicas: 1

      placement:
        constraints:
          - node.role == manager

      resources:
        limits:
          cpus: "1"
          memory: 1024M
       
      # Labels para Traefik - Baileys API
      labels:
        - traefik.enable=true
        - traefik.http.routers.baileys_app.rule=Host(`baileys.b7g.app`)
        - traefik.http.routers.baileys_app.entrypoints=websecure
        - traefik.http.routers.baileys_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.baileys_app.priority=1
        - traefik.http.routers.baileys_app.service=baileys_app
        - traefik.http.services.baileys_app.loadbalancer.server.port=3025
        - traefik.http.services.baileys_app.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.baileys_app.middlewares=sslheader


## --------------------------- ORION --------------------------- ##

volumes:
  chatwoot_storage:
    external: true
    name: chatwoot_storage
  chatwoot_public:
    external: true
    name: chatwoot_public
  chatwoot_mailer:
    external: true
    name: chatwoot_mailer
  chatwoot_mailers:
    external: true
    name: chatwoot_mailers
  chatwoot_redis:
    external: true
    name: chatwoot_redis
  chatwoot_baileys:
    external: true
    name: chatwoot_baileys

networks:
  traefik_public: ## Nome da rede interna
    external: true
    name: traefik_public ## Nome da rede interna
