version: "3.8"

services:
  evolution_v2:
    image: evoapicloud/evolution-api:homolog
    
    networks:
      - traefik_public      # Para exposição via Traefik
      - app_network         # Para comunicação com PostgreSQL/Redis
    
    volumes:
      - evolution_v2_data:/evolution/instances
    
    environment:
      # Network binding - CRÍTICO para Docker
      - HOSTNAME=0.0.0.0
      - PORT=8080
      
      # URLs e configurações básicas
      - SERVER_URL=https://evo.senaia.in
      - DEL_INSTANCE=false
      - DEL_TEMP_INSTANCES=false
      - LANGUAGE=pt_BR
      - TELEMETRY=false
      
      # Provider (desabilitado)
      - PROVIDER_ENABLED=false
      - PROVIDER_HOST=127.0.0.1
      - PROVIDER_PORT=5656
      - PROVIDER_PREFIX=evolution_v2
      
      # Database PostgreSQL
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://chatwoot_database:Ma1x1x0x!!Ma1x1x0x!!@postgres:5432/evolution_database
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_v2
      
      # RabbitMQ (desabilitado conforme sua config)
      - RABBITMQ_ENABLED=false
      - RABBITMQ_URI=amqp://admin:admin@rabbitmq:5672/default
      - RABBITMQ_EXCHANGE_NAME=evolution_v2
      - RABBITMQ_GLOBAL_ENABLED=false
      - RABBITMQ_EVENTS_APPLICATION_STARTUP=false
      - RABBITMQ_EVENTS_INSTANCE_CREATE=false
      - RABBITMQ_EVENTS_INSTANCE_DELETE=false
      - RABBITMQ_EVENTS_QRCODE_UPDATED=false
      - RABBITMQ_EVENTS_MESSAGES_SET=false
      - RABBITMQ_EVENTS_MESSAGES_UPSERT=true
      - RABBITMQ_EVENTS_MESSAGES_EDITED=false
      - RABBITMQ_EVENTS_MESSAGES_UPDATE=false
      - RABBITMQ_EVENTS_MESSAGES_DELETE=false
      - RABBITMQ_EVENTS_SEND_MESSAGE=false
      - RABBITMQ_EVENTS_CONTACTS_SET=false
      - RABBITMQ_EVENTS_CONTACTS_UPSERT=false
      - RABBITMQ_EVENTS_CONTACTS_UPDATE=false
      - RABBITMQ_EVENTS_PRESENCE_UPDATE=false
      - RABBITMQ_EVENTS_CHATS_SET=false
      - RABBITMQ_EVENTS_CHATS_UPSERT=false
      - RABBITMQ_EVENTS_CHATS_UPDATE=false
      - RABBITMQ_EVENTS_CHATS_DELETE=false
      - RABBITMQ_EVENTS_GROUPS_UPSERT=false
      - RABBITMQ_EVENTS_GROUP_UPDATE=false
      - RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE=false
      - RABBITMQ_EVENTS_CONNECTION_UPDATE=true
      - RABBITMQ_EVENTS_CALL=false
      - RABBITMQ_EVENTS_TYPEBOT_START=false
      - RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS=false
      
      # SQS (desabilitado)
      - SQS_ENABLED=false
      - SQS_ACCESS_KEY_ID=
      - SQS_SECRET_ACCESS_KEY=
      - SQS_ACCOUNT_ID=
      - SQS_REGION=
      
      # WebSocket (desabilitado)
      - WEBSOCKET_ENABLED=false
      - WEBSOCKET_GLOBAL_EVENTS=false
      
      # WhatsApp Business
      - WA_BUSINESS_TOKEN_WEBHOOK=evolution
      - WA_BUSINESS_URL=https://graph.facebook.com
      - WA_BUSINESS_VERSION=v20.0
      - WA_BUSINESS_LANGUAGE=pt_BR
      
      # Webhook Global (desabilitado)
      - WEBHOOK_GLOBAL_ENABLED=false
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
      - WEBHOOK_EVENTS_APPLICATION_STARTUP=false
      - WEBHOOK_EVENTS_QRCODE_UPDATED=false
      - WEBHOOK_EVENTS_MESSAGES_SET=false
      - WEBHOOK_EVENTS_MESSAGES_UPSERT=false
      - WEBHOOK_EVENTS_MESSAGES_EDITED=false
      - WEBHOOK_EVENTS_MESSAGES_UPDATE=false
      - WEBHOOK_EVENTS_MESSAGES_DELETE=false
      - WEBHOOK_EVENTS_SEND_MESSAGE=false
      - WEBHOOK_EVENTS_CONTACTS_SET=false
      - WEBHOOK_EVENTS_CONTACTS_UPSERT=false
      - WEBHOOK_EVENTS_CONTACTS_UPDATE=false
      - WEBHOOK_EVENTS_PRESENCE_UPDATE=false
      - WEBHOOK_EVENTS_CHATS_SET=false
      - WEBHOOK_EVENTS_CHATS_UPSERT=false
      - WEBHOOK_EVENTS_CHATS_UPDATE=false
      - WEBHOOK_EVENTS_CHATS_DELETE=false
      - WEBHOOK_EVENTS_GROUPS_UPSERT=false
      - WEBHOOK_EVENTS_GROUPS_UPDATE=false
      - WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE=false
      - WEBHOOK_EVENTS_CONNECTION_UPDATE=true
      - WEBHOOK_EVENTS_LABELS_EDIT=false
      - WEBHOOK_EVENTS_LABELS_ASSOCIATION=false
      - WEBHOOK_EVENTS_CALL=false
      - WEBHOOK_EVENTS_TYPEBOT_START=false
      - WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS=false
      - WEBHOOK_EVENTS_ERRORS=false
      - WEBHOOK_EVENTS_ERRORS_WEBHOOK=
      
      # Configurações de sessão
      - CONFIG_SESSION_PHONE_CLIENT=IDEADI
      - CONFIG_SESSION_PHONE_NAME=Chrome
      - QRCODE_LIMIT=20
      
      # Integrações
      - TYPEBOT_ENABLED=true
      - TYPEBOT_API_VERSION=latest
      - CHATWOOT_ENABLED=true
      - N8N_ENABLED=true
      - EVOAI_ENABLED=true
      
      # Cache Redis
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://:J40geWtC08VoaUqoZ@redis:6379
      - CACHE_REDIS_PREFIX_KEY=evolution_v2
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
      
      # S3 Storage
      - S3_ENABLED=true
      - S3_ACCESS_KEY=5lsFUYQkaj36mjULwzaC
      - S3_SECRET_KEY=gggQxoMDzHlH9AVOFSdB25lftDSoBnWZgeTFyt6g
      - S3_BUCKET=evolution
      - S3_PORT=443
      - S3_ENDPOINT=files.senaia.in
      - S3_USE_SSL=true
      
      # Autenticação
      - AUTHENTICATION_API_KEY=LcXEtOWi3xX0HNFY4EbMT9sPWcMbT1nu
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
    
    # Health check usando Node.js (Evolution API é Node.js)
    healthcheck:
      test: ["CMD-SHELL", "node -e \"const http = require('http'); const req = http.get('http://localhost:8080/', (res) => { if(res.statusCode === 200) { process.exit(0); } else { process.exit(1); } }); req.on('error', () => process.exit(1)); req.setTimeout(5000, () => { req.destroy(); process.exit(1); });\""]
      interval: 30s
      timeout: 120s
      retries: 12
      start_period: 300s
    
    # Labels para Traefik
    deploy:
      mode: replicated
      replicas: 1
      
      placement:
        constraints:
          - node.role == manager
      
      resources:
        limits:
          cpus: "1.5"
          memory: 2048M
        reservations:
          cpus: "0.5"
          memory: 512M
      
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik_public"
        
        # Evolution API service
        - "traefik.http.services.evolution-v2.loadbalancer.server.port=8080"
        - "traefik.http.routers.evolution-v2.rule=Host(`evo.senaia.in`)"
        - "traefik.http.routers.evolution-v2.tls=true"
        - "traefik.http.routers.evolution-v2.tls.certresolver=letsencrypt"
        - "traefik.http.routers.evolution-v2.entrypoints=websecure"
        - "traefik.http.routers.evolution-v2.priority=1"
        
        # Security headers (opcional - pode descomentar depois)
        # - "traefik.http.routers.evolution-v2.middlewares=security-headers"
        # - "traefik.http.middlewares.security-headers.headers.forcestsheader=true"
        # - "traefik.http.middlewares.security-headers.headers.stsincludesubdomains=true"
        # - "traefik.http.middlewares.security-headers.headers.stsseconds=31536000"

volumes:
  evolution_v2_data:
    external: true
    name: evolution_v2_data

networks:
  traefik_public:
    external: true
  app_network:
    external: true
