version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    #depends_on:
    #  - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
    - traefik_public  
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: marcelu.phd@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Ma1x1x0x56
      SCRIPT_NAME: /_admin/pgadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=web
      - traefik.http.routers.pgadmin.service=pgadmin
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - traefik.http.routers.pgadmin.rule=(Host(`localhost`) && PathPrefix(`/_admin/pgadmin`))
      
      - "traefik.http.routers.pgadmin4-http.entrypoints=web"
      - "traefik.http.routers.pgadmin4-http.rule=Host(`pgadmin.aymconsultores.es`)"
      - "traefik.http.routers.pgadmin4.entrypoints=websecure"
      - "traefik.http.routers.pgadmin4.rule=Host(`pgadmin.aymconsultores.es`)"
      - "traefik.http.routers.pgadmin4-http.middlewares=pgadmin4-https@docker"
      - "traefik.http.middlewares.pgadmin4-https.redirectscheme.scheme=https"
      - "traefik.http.routers.pgadmin4.tls=true"
      - "traefik.http.routers.pgadmin4.tls.certresolver=le"
      - "traefik.http.services.pgadmin4.loadbalancer.server.port=80"