version: "3.8"

services:
  yourls:
    image: yourls
    networks:
      - traefik_public
      - app_network
    environment:
      YOURLS_SITE: https://l.SEU_DOMINIO.com.br
      YOURLS_USER: rafael
      YOURLS_PASS: minhaSENHA
      # dados do banco
      YOURLS_DB_HOST: mysql:3306
      YOURLS_DB_NAME: yourls
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: SENHA_ROOT
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.yourls.rule=Host(`l.SEU_DOMINIO.com.br`)
        - traefik.http.routers.yourls.entrypoints=websecure
        - traefik.http.routers.yourls.tls.certresolver=le
        - traefik.http.routers.yourls.service=yourls
        - traefik.http.services.yourls.loadbalancer.server.port=80

networks:
  traefik_public:
    external: true
  app_network:
    external: true
